
index:
  path: /
  defaults: { _controller: 'App\Controller\DefaultController::index' }

info:
  path: /info
  defaults: { _controller: 'App\Controller\DefaultController::info' }

command_list:
  path: /command
  controller: App\Controller\CommandController::list

command_uptime:
  path: /command/uptime
  controller: App\Controller\CommandController::uptime

command_translate:
  path: /command/translate/{x}/{y}
  controller: App\Controller\CommandController::translate

command_rotate:
  path: /command/rotate/{d}
  controller: App\Controller\CommandController::rotate

command_reset:
  path: /command/reset
  controller: App\Controller\CommandController::reset

command_restart_motion:
  path: /command/restart-motion
  controller: App\Controller\CommandController::restartMotion
